/*
 *Classe qui permet de saisir une offre de stage
 */
package my.MenuSaisie;


import javax.swing.JOptionPane;
import projetoffresstage.MainProjet;
import projetoffresstage.Entreprise;
import projetoffresstage.OffreStage;

/**
 *
 * @author Audrey
 */
public class MenuSaisie extends javax.swing.JFrame {

    /**
     * Creates new form MenuSaisie
     */
    public MenuSaisie() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitre = new javax.swing.JLabel();
        txtNom = new javax.swing.JLabel();
        txtNomEntreprise = new javax.swing.JComboBox();
        txtDomaine = new javax.swing.JLabel();
        txtDomaineE = new javax.swing.JComboBox();
        txtLibelle = new javax.swing.JLabel();
        txtLibelleO = new javax.swing.JTextField();
        txtDate = new javax.swing.JLabel();
        txtDateDeb = new javax.swing.JTextField();
        txtDuree = new javax.swing.JLabel();
        txtDureeO = new javax.swing.JTextField();
        txtChemin = new javax.swing.JLabel();
        txtCheminO = new javax.swing.JTextField();
        txtDescription = new javax.swing.JLabel();
        txtDescritpionO = new javax.swing.JScrollPane();
        txtDescriptionO = new javax.swing.JTextArea();
        btnEnvoyer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 188, 193));

        txtTitre.setText("SAISIE D'UNE OFFRE DE STAGE");

        txtNom.setText("Nom de l'entreprise");

        for(Entreprise uneEntreprise : MainProjet.lesEntreprises){

            txtNomEntreprise.addItem(uneEntreprise.getRaisonSocial());
        }
        txtNomEntreprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEntrepriseActionPerformed(evt);
            }
        });

        txtDomaine.setText("Domaine de l'offre");

        txtDomaineE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Développeur", "Réseaux", "Base de données" }));

        txtLibelle.setText("Libellé de l'offre");

        txtDate.setText("Date de début du stage");

        txtDuree.setText("Durée");

        txtDureeO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDureeOActionPerformed(evt);
            }
        });

        txtChemin.setText("Chemin de stockage de l'offre de stage");

        txtDescription.setText("Description de l'offre");

        txtDescriptionO.setColumns(20);
        txtDescriptionO.setRows(5);
        txtDescritpionO.setViewportView(txtDescriptionO);

        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDomaineE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitre))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtLibelle)
                                .addGap(18, 18, 18)
                                .addComponent(txtLibelleO, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDomaine)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNom)
                                .addGap(47, 47, 47)
                                .addComponent(txtNomEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtChemin)
                                .addGap(33, 33, 33)
                                .addComponent(txtCheminO, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(txtDuree)
                                .addGap(40, 40, 40)
                                .addComponent(txtDureeO, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(txtDescription))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(txtDescritpionO, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnEnvoyer)
                        .addGap(129, 129, 129)
                        .addComponent(btnAnnuler)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNom)
                    .addComponent(txtNomEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomaine)
                    .addComponent(txtDomaineE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibelleO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibelle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate)
                    .addComponent(txtDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuree)
                    .addComponent(txtDureeO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChemin)
                    .addComponent(txtCheminO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescritpionO, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnvoyer)
                    .addComponent(btnAnnuler))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
      
        // Controle du formulaire d'envoie d'une entreprise.
        if(txtLibelleO.getText().isEmpty()
                ||txtDescriptionO.getText().isEmpty()
                ||txtDateDeb.getText().isEmpty()
                ||txtDureeO.getText().isEmpty()
                ||txtCheminO.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Il faut remplir tout les champs.",
                    "Message",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
            // Envoie des données a la collection offre de stage.
            OffreStage o = new OffreStage (((String) txtNomEntreprise.getSelectedItem()),
                    txtLibelleO.getText(),txtDescriptionO.getText(),
                    (String)txtDomaineE.getSelectedItem(),txtDateDeb.getText(),
                    txtDureeO.getText(), txtCheminO.getText());
            MainProjet.lesOffres.add(o);
            
            String nom = evt.getActionCommand();
            if (nom.equals("Envoyer"))
                JOptionPane.showMessageDialog(this, "Votre demande a bien été envoyé !",
                        "Message",
                        JOptionPane.INFORMATION_MESSAGE);
            // Fermeture de la fenêtre.
            this.dispose();
        }
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void txtDureeOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDureeOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDureeOActionPerformed

    private void txtNomEntrepriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEntrepriseActionPerformed
      
    }//GEN-LAST:event_txtNomEntrepriseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSaisie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtChemin;
    private javax.swing.JTextField txtCheminO;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtDateDeb;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JTextArea txtDescriptionO;
    private javax.swing.JScrollPane txtDescritpionO;
    private javax.swing.JLabel txtDomaine;
    private javax.swing.JComboBox txtDomaineE;
    private javax.swing.JLabel txtDuree;
    private javax.swing.JTextField txtDureeO;
    private javax.swing.JLabel txtLibelle;
    private javax.swing.JTextField txtLibelleO;
    private javax.swing.JLabel txtNom;
    private javax.swing.JComboBox txtNomEntreprise;
    private javax.swing.JLabel txtTitre;
    // End of variables declaration//GEN-END:variables
}
